[package]
url = "https://github.com/p11-glue/p11-kit.git"
ref = "0.25.5"

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = ["libffi@3.4.8"]
dev_dependencies = [
    "macros@1.20.2",
    "libtool@2.5.4",
    "gettext@0.25",
    "pkgconf@2.4.3",
]
options = ["--without-libtasn1"]

# Note:
# This library support linux only.
