[package]
url = "https://gitlab.gnome.org/GNOME/glib.git"
ref = "2.84.1"

[[build_configs]]
build_system = "meson"
build_tools = ["python3:setuptools"]
options = ["-Dlibmount=enabled"]
dependencies = ["util-linux@2.41", "libffi@3.4.8", "zlib@1.3.1"]
dev_dependencies = ["pkgconf@2.4.3", "gettext@0.25"]
